# Generated by Django 5.1.4 on 2025-02-17 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('aadhar', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='worker_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('working_date', models.DateField()),
                ('per_day_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmer_aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.farmer')),
                ('worker_aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
            ],
        ),
    ]
